### ISSUE TITLE
how can I train the model in the ShanghaiTech dataset?

### ISSUE THREAD

**Issue by niepei** [Pongpisit-Thanasutives/Variations-of-SFANet-for-Crowd-Counting#12]
we generate training data through preprocess_dataset.py in BL code, but during training,  we find the issue `nearest_dis = np.clip(keypoints[:, 2], 4.0, 128.0) IndexError: index 2 is out of bounds for axis 1 with size 2`. And the shape of  our keypoints is 2.  So I want to ask how you train the model in the ShanghaiTech dataset.

**Comment by Pongpisit-Thanasutives** [comment]
I have added the BL code for preprocessing SH datasets. Please try to use it with the correct data paths.

**Comment by niepei** [comment]
Thank you for the code.
