### ISSUE TITLE
find dis

### ISSUE THREAD

**Issue by KRYSTALLJY** [Pongpisit-Thanasutives/Variations-of-SFANet-for-Crowd-Counting#13]
Hi,
I noticed in find_dis:
dis = np.mean(np.partition(dis, 3, axis=1)[:, 1:4], axis=1, keepdims=True)

image with people less than 4 is illegal?

**Comment by Pongpisit-Thanasutives** [comment]
Yes, unfortunately, we have followed the proposed method in the MCNN paper (CVPR 2016) to calculate the average distance of each head to the 3 nearest heads. However, you can modify the code to follow your heuristics instead.

**Comment by KRYSTALLJY** [comment]
> Yes, unfortunately, we have followed the proposed method in the MCNN paper (CVPR 2016) to calculate the average distance of each head to the 3 nearest heads. However, you can modify the code to follow your heuristics instead.

If I assign a fix value for image less than 3 ppl to do gaussian filter, does it affect the final performance?

**Comment by KRYSTALLJY** [comment]
> > Yes, unfortunately, we have followed the proposed method in the MCNN paper (CVPR 2016) to calculate the average distance of each head to the 3 nearest heads. However, you can modify the code to follow your heuristics instead.
> 
> If I assign a fix value for image less than 3 ppl to do gaussian filter, does it affect the final performance?

Besides, If I want a good performance on different dataset, what should I do to improve the generalization? Do you have any advices? Thanks.

**Comment by Pongpisit-Thanasutives** [comment]
My advice would be to conduct an ablation study on ASSP and CAN. Since both modules also increase the network complexity, possibly leading to overfitting. You could find the combination which fits your dataset (train + test) nature.
