### ISSUE TITLE
Inconsistent shapes of conv4, conv5,feature in Backend()'s forwarding in MSegNet 

### ISSUE THREAD

**Issue by Mozijie255** [Pongpisit-Thanasutives/Variations-of-SFANet-for-Crowd-Counting#20]
![1622190972(1)](https://user-images.githubusercontent.com/66461696/119956668-e96a6200-bfd3-11eb-8fb1-e99216ca3216.png)
![1622190951(1)](https://user-images.githubusercontent.com/66461696/119956676-ed967f80-bfd3-11eb-82a5-0b70c186df91.png)

Anybody come across this problem while using random input picture to generate density map through M-SegNet? why the  shape[2] of these 3 tensor differ?

**Comment by Mozijie255** [comment]
I think I got it...it seems that the input img's size must be able to be divided by 16 due to the setting of downsampling, otherwise there will be some inconsistency during upsampling

**Comment by Pongpisit-Thanasutives** [comment]
@Mozijie255 Yes, you're right! It depends on how many times the max-pooling operation is used in the encoder part.
So, 4 times => the image size must be divided by 2^4.
