### ISSUE TITLE
the version of pytorch

### ISSUE THREAD

**Issue by Zuojianhao** [Pongpisit-Thanasutives/Variations-of-SFANet-for-Crowd-Counting#6]
Hello,thanks for your greaat job. But I find that pytorch1.2.0 don't have "default_collate" in "dataloadder". Please tell me the version of your pytorch. Best wishes.

**Comment by Pongpisit-Thanasutives** [comment]
I think the latest version of Pytorch or Pytorch >= 1.4 would be fine.

**Comment by Zuojianhao** [comment]
ok,thank you very much
