### ISSUE TITLE
cannot use the pretrain model

### ISSUE THREAD

**Issue by ckqsars** [Pongpisit-Thanasutives/Variations-of-SFANet-for-Crowd-Counting#9]
I want to use the pretain model to test the Visualization code.
But have erros in loading state_dict for Model:
the error is miss key of vgg's weight and bias.
So How can I use the pretrain model?

**Comment by Pongpisit-Thanasutives** [comment]
I think you need the pretrained weights for M_SegNet* to test the visualization code. Here it is https://drive.google.com/file/d/1fGuH4o0hKbgdP1kaj9rbjX2HUL1IH0oo/view?usp=sharing. Note that the weights for SHA and SHB are for M_SegNet (not M_SegNet*).
